# Generated by Django 3.2.4 on 2021-08-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210805_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bags',
            new_name='original_bag',
        ),
    ]
